# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    environment:
      - MIX_ENV: test
    docker:
      - image: circleci/elixir:1.8

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix credo --strict
      - run: mix coveralls.circle
